### ISSUE TITLE
Definition of value attribute in Preselection Desciptor

### ISSUE THREAD

**Issue by paulhiggs** [MPEGGroup/DASHSchema#101]
Clause 5.3.10.2 defines the value space of the @value attribute to be constrained as 

> The syntax for the value field of the Preselection descriptor shall follow the PRESELECTION-DESCRIPTOR-VALUE as defined in the following ABNF notation according to IETF RFC 5234:

This should read "The syntax for the `@value` ~~field~~ <em>attribute</em> of the Preselection descriptor shall follow the PRESELECTION-DESCRIPTOR-VALUE as defined in the following ABNF notation according to IETF RFC 5234:"

**Comment by mikedo** [comment]
Agreed

**Comment by haudiobe** [comment]
Updated in FDIS text.

**Comment by paulhiggs** [comment]
Fixed in latest FDIS (2021-06-17)
