### ISSUE TITLE
datatype of PatchLocationType@ttl is inconsistent with FDIS

### ISSUE THREAD

**Issue by paulhiggs** [MPEGGroup/DASHSchema#104]
5th edition FDIS defines (in Table 49) the datatype of the `@ttl` attribute in `PatchLocationType` as `xs:double`, but this is defined incorrectly in the 5th edition schema as `type="xs:unsignedInt"`

**Comment by paulhiggs** [comment]
@technogeek00

**Comment by mikedo** [comment]
Follow the text.
