### ISSUE TITLE
cardinality of PatchLocation@ttl in DASH 5th edition

### ISSUE THREAD

**Issue by paulhiggs** [MPEGGroup/DASHSchema#105]
The semantic description of the `PatchLocation@ttl` attribute is defined in clause 5.15.2 table 49 as 

|Element or Attribute Name | Use | Description|
|-- | -- | --|
| `@ttl` | O | specifies the time period duration (in seconds) starting from MPD@publishTime until the MPD patch document is at least available at the indicated location above. For details refer to the processing model in subclause 5.14.4.<br/>If **not present**, the value is unknown.|

however it is schematically defined as 
````
<xs:attribute name="ttl" type="xs:double" default="0" use="required"/>
````

thus, there is no possibility for the `ttl` attribute to be **not present**

**Comment by paulhiggs** [comment]
@technogeek00

**Comment by mikedo** [comment]
The text is clear.  @default is ignored anyway, but should be removed for accuracy.

**Comment by technogeek00** [comment]
concur with @mikedo

**Comment by paulhiggs** [comment]
`default="0"` is removed from the schema - just needs updating in the FDIS

**Comment by mikedo** [comment]
The electronic schema still conflicts with the spec text which is clear that it is optional.

**Comment by technogeek00** [comment]
I can propose a PR change later tonight

**Comment by mikedo** [comment]
OK.  Don't merge it yet just in case the intent turns out to be the way it is.

**Comment by technogeek00** [comment]
@mikedo available as #114

**Comment by haudiobe** [comment]
FDIS update: removed `"default = 0" use = "required"`

**Comment by paulhiggs** [comment]
Schema updated
