### ISSUE TITLE
@selectionPriority has a default value

### ISSUE THREAD

**Issue by paulhiggs** [MPEGGroup/DASHSchema#108]
5th edition FDIS defines `RepresentationBaseType@selectionPriority` as optional, but with a default value of **1**

5th edition schema (or schema fragment in clause 5.3.6.3) does not include this default `<xs:attribute name="selectionPriority" type="xs:unsignedInt"/>`

**Comment by paulhiggs** [comment]
update to `<xs:attribute name="selectionPriority" type="xs:unsignedInt" default="1"/>` needed.

**Comment by mikedo** [comment]
Agreed. Follow the text.

**Comment by paulhiggs** [comment]
Schema updated - schema fragment in FDIS to be aligned.
