### ISSUE TITLE
Switching@type has a default value

### ISSUE THREAD

**Issue by paulhiggs** [MPEGGroup/DASHSchema#109]
The `Switching@type` attribute is defined in Table 6 has optional and having a default value of 'media'.

This default is not included schematically (`<xs:attribute name="type" type="SwitchingTypeType"/>`) 

Should be `<xs:attribute name="type" type="SwitchingTypeType" default="media"/>` if the XML parser is expected to provide that value.

**Comment by mikedo** [comment]
Agreed.
