### ISSUE TITLE
inconsistent default value definition for ExtendedUrlInfoType@headerParamSource 

### ISSUE THREAD

**Issue by paulhiggs** [MPEGGroup/DASHSchema#111]
The semantic definition of the `@headerParamSource` optional attribute in Table I.3 (clause I.3.2) states that the default value is `"segemnt"` but the schema fragment in clause I.3.3 has `<xs:attribute name="headerParamSource" type="xs:string" default=""/>`

**Comment by mikedo** [comment]
Add proper default value.
