### ISSUE TITLE
Example_G14 does not have a closing </Period>

### ISSUE THREAD

**Issue by paulhiggs** [MPEGGroup/DASHSchema#13]
The `</Period>` is missing

**Comment by mikedo** [comment]
Then why does it validate?  There is something else wrong.

**Comment by paulhiggs** [comment]
Did not validate for me (on the Amd.5 branch) so I added it
The original commit had this...
`</AdaptationSet>
	<UTCTiming schemeIdUri="urn:mpeg:dash:utc:http-xsdate:2014" value="https://example.com/iso"/>
	<LeapSecondInformation availabilityStartLeapOffset="0" nextAvailabilityStartLeapOffset="1" nextLeapChangeTime="2020-01-01T00:00:00"/>
</MPD>`

**Comment by mikedo** [comment]
Apologies, I thought this was an existing example.
