### ISSUE TITLE
G8 has no schema header (ns, etc)

### ISSUE THREAD

**Issue by mikedo** [MPEGGroup/DASHSchema#3]

**Comment by paulhiggs** [comment]
The change for example_G8 includes a namespace definition for drm: (`xmlns:drm="http://example.net/052011/drm"`) but this is not used in the example. Better to remove it than lead to any uncertainty.

**Comment by mikedo** [comment]
Over-zealous copy/paste on my part to fix the missing top level attributes. Will delete.
