### ISSUE TITLE
Problems with Example G.11

### ISSUE THREAD

**Issue by haudiobe** [MPEGGroup/DASHSchema#37]
I am unclear why https://github.com/MPEGGroup/DASHSchema/blob/master/example_G11_remote.period.xml includes and MPD element? It should only the Period element.
I understand that then this does not validate, but the document itself cannot contain an MPD element as the Period is added directly.
I removed the MPD element in the remote part. Can this also be done in the examples on github and in the updated packages?

Also, the document should not be an mpd
In the XML this should be replaced
\<Period xlink:href="example_G11_remote.period.mpd" xlink:actuate="onRequest" xmlns:xlink="http://www.w3.org/1999/xlink"/>"
With
\<Period xlink:href="example_G11_remote.period.xml" xlink:actuate="onRequest" xmlns:xlink="http://www.w3.org/1999/xlink"/>"
Thanks
Thomas

**Comment by sdp198** [comment]
See PR #39

**Comment by mikedo** [comment]
@haudiobe Right on both accounts. 
@sdp198  But I'd prefer to fix it a bit more elegantly - define a referenceable Period element in the DASH_MPD and then put the necessary validation junk on the Period element.
Xlink processors are just going to have to cope with the XML header preceding Period, and I'd prefer to include it in the example to emphasize that.

**Comment by mikedo** [comment]
OK, but see github issue.

**Comment by mikedo** [comment]
Fixed per the above.
