### ISSUE TITLE
DASH-MPD-UP

### ISSUE THREAD

**Issue by haudiobe** [MPEGGroup/DASHSchema#40]
In DASH-MPD-UP, the xlink href needs to be updated as well

		<xs:attribute ref="xlink:href"/>
		<xs:attribute ref="xlink:actuate" default="onRequest"/>
		<xs:attribute ref="xlink:type" fixed="simple"/>
		<xs:attribute ref="xlink:show" fixed="embed"/>

**Comment by mikedo** [comment]
Your email of Friday at 11:13 pm PDT only adds two xlink (not 4) attributes, which is consistent with the I.2 text semantics table. It's hard to reconcile the "answer" in this issue with that email. I'll proceed with the email since that aligns with the text.

**Comment by mikedo** [comment]
Thanks for dong the first part. The second part needed a better (in my opinion) resolution. I was not confident in using the "cherry pick" feature so closed this and merged changes separately.

**Comment by haudiobe** [comment]
Xlink needs to have 4 attributes. I added the the missing 2

**Comment by mikedo** [comment]
I understand that you want that. But unless I am confused, which is possible, the draft doc semantics table does not say that - only the 2 already defined attributes. It is not sufficient to change the xml snippet withoit explanation.

Sent from my phone

On Aug 11, 2019, at 4:00 PM, Thomas Stockhammer <notifications@github.com<mailto:notifications@github.com>> wrote:


Xlink needs to have 4 attributes. I added the the missing 2

**Comment by mikedo** [comment]
Changed in FDIS-4th-Ed-20190812
