### ISSUE TITLE
[4th Ed AMD1 w19282] @segmentAlignment and @subSegmentAlignment

### ISSUE THREAD

**Issue by mikedo** [MPEGGroup/DASHSchema#48]
The type of this changed form xs:unsignedInt to xs:boolean which was backwards incompatible. Since it used to be xs:boolean, the safest thing is to change it to a union of both.

**Comment by sdp198** [comment]
In the 2nd edition schema I have downloaded in the 2014 electronic inserts zip the type was "ConditionalUintType", with the following definition in the schema:
	
	<xs:simpleType name="ConditionalUintType">
		<xs:union memberTypes="xs:unsignedInt xs:boolean"/>
	</xs:simpleType>

**Comment by paulhiggs** [comment]
Some text may be needed to restrict the boolean value to 'true'|'false' since 0 and 1 are permitted by definition of `boolean`
```3.2.2.1 Lexical representation
  An instance of a datatype that is defined as ·boolean· can have the 
  following legal literals {true, false, 1, 0}. ```

**Comment by mikedo** [comment]
Paul Higgs commented on 16-Jan but it was not logged for some reason:
> Some text may be needed to restrict the boolean value to 'true'|'false' since 0 and 1 are permitted by definition of boolean. An instance of a datatype that is defined as ·boolean· can have the following legal literals {true, false, 1, 0}. ```

When it was an integer, what was the range and what did it mean?  Maybe it doesn't matter?

**Comment by paulhiggs** [comment]
I don't know what happened to that comment I wrote back in January. The 4th edition mentions this carrying values "false", "true", "TRUE" and "share the same value" (in the last paragraphs of 5.3.11.5.2 and 5.3.11.5.3

**Comment by mikedo** [comment]
Leaving open for now to eventually resolve the 0/1 ambiguity.

**Comment by paulhiggs** [comment]
5th Edition Schema (with `ConditionalUintType`) and 5th Edition Standard (still has `xs:boolean` for `AdaptationSetType@segmentAlignment` and `AdaptationSetType@subSegmentAlignment`)

Standard is incorrect, since 5.10.3.3.6 says "NOTE 2 If **AdaptationSet**@SegmentAlignment is an integer larger than 1..."

**Comment by mikedo** [comment]
Duplicate of #87
