### ISSUE TITLE
External xlink.xsd source now too obscure

### ISSUE THREAD

**Issue by mikedo** [MPEGGroup/DASHSchema#55]
In 4th Ed, the ISO editor objected to and removed the Annex B text reference to the W3C source for the xlink.xsd schema. In 4th AMD1, we now have a new external schema IETF patch-ops.xsd. Suggest using absolute URLs for the import. Users can replace with a relative (local copy) if they wish, but at least it would be unambiguous exactly what schema is needed and where to acquire it.

**Comment by paulhiggs** [comment]
added a [comment](https://github.com/MPEGGroup/DASHSchema/pull/57#issuecomment-616963230) on the PR
