### ISSUE TITLE
@profiles not validating more than one URI

### ISSUE THREAD

**Issue by mikedo** [MPEGGroup/DASHSchema#76]
Did we lose #46 in a more recent commit?

**Comment by mikedo** [comment]
This is a new problem. The current regex allows either a single URN or a single URL, but not more than one URI.
Also, regex101.com reports that neither the original regex nor the current one is valid regex syntax.

**Comment by paulhiggs** [comment]
Im happy to look into this, which branch should I look at?

The `<pattern>` in for `ListOfProfilesType` seems valid in XMLspy, but does not seem to allow URLs anywhere

**Comment by paulhiggs** [comment]
Ideally, we need to define ENTITY values for `uri` and `url`, Then the pattern becomes 
`(&uri;|&url)(,(&uri;|&url))*` (or for humans - a uri or a url followed by 0 or more sequences of a comma followed by a uri or a url)

**Comment by mikedo** [comment]
I don't know the pedigree of regex101.com, but it's really interesting tool. Copy the regex into it and see what it says. Seems like it needs fixing.
I found a problem with the @profiles string I was trying to validate - the separator was both a comma and a space. Removing the spaces (comma only) allowed it to validate.
Be sure you have the schema from the master branch. It works with http://
And then there is this regex to consider, which is different: http://lists.xml.org/archives/xml-dev/200108/msg00891.html

**Comment by paulhiggs** [comment]
> the separator was both a comma and a space. Removing the spaces (comma only) allowed it to validate.

If whitespace is permitted in a comma separated list (humans need these - for computers its just a burden that needs to be "trimmed") then add  `\s*` after the comma

**Comment by paulhiggs** [comment]
On Regular Expressions vs XML Patterns.

- XSD has `&#xA0;` which in regex is expressed as `\xA0`
- XSD does not require the slash ('/`) to be escaped but regex does, i.e. `\/`

so the XML pattern `(([A-Za-z0-9\-\._~&#xA0;-&#xFF;]|(&#37;[0-9A-Fa-f][0-9A-Fa-f])|[!$&amp;/#'()*+;=:@]))+(,(([A-Za-z0-9\-\._~&#xA0;-&#xFF;]|(&#37;[0-9A-Fa-f][0-9A-Fa-f])|[!$&amp;/#'()*+;=:@]))*)*` becomes `(([A-Za-z0-9\-\._~\xA0-\xFF]|(&#37;[0-9A-Fa-f][0-9A-Fa-f])|[!$&amp;\/#'()*+;=:@]))+(,(([A-Za-z0-9\-\._~\xA0-\xFF]|(&#37;[0-9A-Fa-f][0-9A-Fa-f])|[!$&amp;\/#'()*+;=:@]))*)*` in regex

While this pattern is "complicated", you can see that a URIchar is `(([A-Za-z0-9\-\._~&#xA0;-&#xFF;]|(&#37;[0-9A-Fa-f][0-9A-Fa-f])|[!$&amp;/#'()*+;=:@]))` so this can be read as 
`(URIchar)+(,(URIchar)*)*`

The (URIchar)* -- i.e. zero or more URI chars --- should be (URIchar)+ otherwise `paul,,,,` is valid

**Comment by mikedo** [comment]
> If whitespace is permitted in a comma separated list (humans need these - for computers its just a burden that needs to be "trimmed") then add \s* after the comma

No, I think if it is comma-separated, it is correct as is (no space). This may trip up a few folks but hopefully we can modify an example per #77 to make it clearer.

OK, ready to do a PR on dev?  We could alert DASH-IF folks and maybe Ece or someone could check  it against the existing MPD assets.

**Comment by paulhiggs** [comment]
It looks like the pattern on the `dev` branch has the correct pattern, i.e. `(([A-Za-z0-9\-\._~&#xA0;-&#xFF;]|(&#37;[0-9A-Fa-f][0-9A-Fa-f])|[!$&amp;/#'()*+;=:@]))+(,(([A-Za-z0-9\-\._~&#xA0;-&#xFF;]|(&#37;[0-9A-Fa-f][0-9A-Fa-f])|[!$&amp;/#'()*+;=:@]))*)*`

Using DTD Entities would have something like this
````
<!DOCTYPE schema [
	<!ENTITY pct "&#x25;">		<!-- % -->
	<!ENTITY quot "&#x22;">		<!-- " -->
	
	<!-- RFC 1738 -->
	<!ENTITY lowalpha "a-z">
	<!ENTITY hialpha "A-Z">
	<!ENTITY alpha "&lowalpha;&hialpha;">
	<!ENTITY digit "0-9">
	<!ENTITY safe "$\-_.+">
	<!ENTITY extra "!*(),&quot;">
	<!ENTITY national "{}|\\^~[]`">
	<!ENTITY punctuation "<>#&pct;&quot;">
	<!ENTITY x-reserved ";/?:@=">
	<!ENTITY reserved "&x-reserved;&amp;">
	<!ENTITY hex "&digit;A-Fa-f">
	<!ENTITY escape "&pct;&hex;&hex;">
	<!ENTITY unreserved "&alpha;&digit;&safe;&extra;">
	<!ENTITY uchar "&unreserved;&escape;">
	<!ENTITY xchar "&unreserved;&reserved;&escape;">
	<!ENTITY digits "[&digit;]+">

	<!ENTITY chrs "&unreserved;&pct;&amp;~;=:@">
	
	<!ENTITY Scheme "[&alpha;][&alpha;&digit;+\-.]*">
	<!ENTITY User "([&unreserved;&pct;&amp;~;=]+)">
	<!ENTITY Password "([&unreserved;&pct;&amp;~;=]+)">
	<!ENTITY NamedHost "[&alpha;&digit;&pct;\-._~]+">
	<!ENTITY IPv6Host "\[[a-f&digit;:.]+\]">
	<!ENTITY IPvFutureHost "\[v[a-f&digit;][&unreserved;&pct;&amp;~;=:]+\]">
	
	<!ENTITY DecimalByte "([&digit;]|[1-9][&digit;]|1[&digit;]{2}|2[0-4][&digit;]|25[0-5])">
	
	<!ENTITY Port "(:([&digit;]{1,4}|[1-5][&digit;]{4}|6[0-4][&digit;]{3}|65[0-4][&digit;]{2}|655[0-2][&digit;]|6553[0-5]))">
	
	<!ENTITY Path "(/[&chrs;]+)">
	
	<!ENTITY AuthorityAndPath "//(&User;(:&Password;)?@)?(&NamedHost;|&IPv6Host;|&IPvFutureHost;)&Port;?&Path;*/?">
	<!ENTITY PathNoAuthority "(/?[&chrs;]+&Path;*/?)">
	<!ENTITY RelativePath "[&chrs;]+&Path;*">
	<!ENTITY AbsolutePath "&Path;+">
	<!ENTITY Query "(\?[&chrs;/?]*)">
	<!ENTITY Fragment "(#[&chrs;/?]*)">


	<!-- IETF RFC 2141 -->
	<!ENTITY NamespaceID "[&alpha;&digit;][&alpha;&digit;-]{1,31}">
	
	<!ENTITY NSS-others "()+,\-\.:=@;$_!*'">
	<!ENTITY NSS-reserved "&pct;/?#">
	<!ENTITY NSS-URNchars "&hialpha;&lowalpha;&digit;&NSS-others;&NSS-reserved;">
	<!ENTITY NamespaceSpecific "[&NSS-URNchars;]+"> 

	
	<!ENTITY URN "urn:&NamespaceID;:&NamespaceSpecific;">
	<!ENTITY URL "(&Scheme;:(&AuthorityAndPath;|&PathNoAuthority;)|(&RelativePath;/?|&AbsolutePath;/?))&Query;?&Fragment;?"
]>


	<xs:simpleType name="ListOfProfilesType">
		<xs:restriction base="xs:string">
			<xs:pattern value="(&URL;|&URL;)(,(&URN;|&URL;))*"/>
		</xs:restriction>
	</xs:simpleType>
````

**Comment by mikedo** [comment]
FYI, the regex slash issue was found by DASH-IF and fixed last summer I think.  I (still) like your approach above.

**Comment by paulhiggs** [comment]
Regex for IPv6 address
````
(
	([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|          # 1:2:3:4:5:6:7:8
	([0-9a-fA-F]{1,4}:){1,7}:|                         # 1::                              1:2:3:4:5:6:7::
	([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|         # 1::8             1:2:3:4:5:6::8  1:2:3:4:5:6::8
	([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|  # 1::7:8           1:2:3:4:5::7:8  1:2:3:4:5::8
	([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|  # 1::6:7:8         1:2:3:4::6:7:8  1:2:3:4::8
	([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|  # 1::5:6:7:8       1:2:3::5:6:7:8  1:2:3::8
	([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|  # 1::4:5:6:7:8     1:2::4:5:6:7:8  1:2::8
	[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|       # 1::3:4:5:6:7:8   1::3:4:5:6:7:8  1::8  
	:((:[0-9a-fA-F]{1,4}){1,7}|:)|                     # ::2:3:4:5:6:7:8  ::2:3:4:5:6:7:8 ::8       ::     
	fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|     # fe80::7:8%eth0   fe80::7:8%1     (link-local IPv6 addresses with zone index)
	::(ffff(:0{1,4}){0,1}:){0,1}
	((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}
	(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|          # ::255.255.255.255   ::ffff:255.255.255.255  ::ffff:0:255.255.255.255  (IPv4-mapped IPv6 addresses and IPv4-translated addresses)
	([0-9a-fA-F]{1,4}:){1,4}:
	((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}
	(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])           # 2001:db8:3:4::192.0.2.33  64:ff9b::192.0.2.33 (IPv4-Embedded IPv6 Address)
)
````
Regex for IPv4 address is easier
````	
	((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])
````

**Comment by paulhiggs** [comment]
My commit which uses Entity values to represent "a comma separated list of URNs or URLs" to ensure that repeated values in the pattern use the same defined name (a.la. C #macro). This should be easier to maintain and validate through ci in the future
