### ISSUE TITLE
it's desirable to have an example that has more than one @profiles URI and with http://

### ISSUE THREAD

**Issue by mikedo** [MPEGGroup/DASHSchema#77]

**Comment by paulhiggs** [comment]
This would need to be done in a schema test vector and not an `example_XXX.xml` since all MPEG defined profiles fall under urn:mpeg:

**Comment by mikedo** [comment]
This was overtaken by events as AMD1 (aka 5th Ed) has such an example of both URN and URL.  @profiles is defined as a URI so a URL is permitted syntax, even though the profile value is not defined by MPEG.

**Comment by paulhiggs** [comment]
As new [example-G19.mpd](https://github.com/MPEGGroup/DASHSchema/blob/5th-Ed/example_G19.mpd) contains multiple values in the MPD@profiles attribute, we can close this issue.
