### ISSUE TITLE
Period should not be permitted to be a top level element

### ISSUE THREAD

**Issue by mikedo** [MPEGGroup/DASHSchema#78]
In the 4th Ed, Period was added as a top-level element (in addition to MPD). This was in response to a request to formalize the content of an xlink remote entity element. Although the goal was good, a document that has only Period in it is not in fact an MPD. Period should be removed as a top-level element, and #59 resolved fully and in another way.

**Comment by mikedo** [comment]
MPEG DASH AHG agreed. See: http://mpegx.int-evry.fr/software/MPEG/Systems/DASH/spec/issues/38 (MPEG only)

**Comment by paulhiggs** [comment]
Fixed with #90 and #91
