### ISSUE TITLE
Issue related to 3D audio from MPEG-H

### ISSUE THREAD

**Issue by LifeIsStrange** [MPEGGroup/DASHSchema#79]
MPEG-H is working on a new audio codec (mostly about improving 3d audio support)
https://en.m.wikipedia.org/wiki/MPEG-H_3D_Audio
I don't know if MPEG is working on another audio codec in parallel. 

The issue has of course nothing to do with DASHSchema but I can't find where to contact the engineers that work on audio codecs at MPEG.
I see that you have repositories for collecting issues relative to a codec such as 
> Official MPEG repository to discuss issues on MIAF
MPEG-H 3D audio probably needs one too!

Anyway, here's what's my issue is about:
I believe that researchers have made a breakthrough discovery that could allow to evolve audio codecs (and possibly h266 too but I'm not sure)
I am talking about this:
Experiment using Fast inverse chip z-transform

I'm not an expert, but this seems like a major discovery in signal processing!

From the comments I read:
*Sounds like a pretty awesome milestone to me. So, perhaps in the near future, new compression schemes might allow for reduced mp3 and mp4 file sizes, which means that for the same bandwidth we could see increased resolution/ higher frame rates*

And

*It should be a O(n log n) rather than O(n^2), so the speed increase for large n, which can be common n signal processing, is real.*

Comments:
https://news.ycombinator.com/item?id=21230757
Source:
https://m.techxplore.com/news/2019-10-year-old-puzzle.html

**Comment by mikedo** [comment]
Inappropriate content.

**Comment by LifeIsStrange** [comment]
@mikedo true but as an MPEG member you could still redirect me to the correct place.
It seems that the correct place (a MPEG-H 3D audio repository) does not exist. 
With such a policy you will loose a lot of external contributions which is a sad and mediocre loss.

**Comment by paulhiggs** [comment]
Turn up to ISO SC29 meetings and make a proposal.

**Comment by LifeIsStrange** [comment]
@paulhiggs you mean like meeting them IRL in Switzerland https://www.itscj.ipsj.or.jp/sc29/29w32901.htm ?
^^ that would be fun but I have not the motivation and I live too far away. 
Isn't there simply an email address or a slack channel?

**Comment by LifeIsStrange** [comment]
I found it!!
mpeg-h-techsupport@dmt.fraunhofer.org
From https://www.mpegh.com/en/home/
Thanks, the issue is resolved
