### ISSUE TITLE
ensure AMD1 text includes the XML schema for patch

### ISSUE THREAD

**Issue by mikedo** [MPEGGroup/DASHSchema#81]
See https://github.com/Dash-Industry-Forum/MPEG/issues/25

The schema here is the latest. Just copy the XML into the next output of AMD1.

**Comment by paulhiggs** [comment]
I think we have this now in [DASH-MPD-PATCH.xsd](https://github.com/MPEGGroup/DASHSchema/blob/5th-Ed/DASH-MPD-PATCH.xsd)
