### ISSUE TITLE
[4th Ed] xs:anyUri would benefit from stronger typing

### ISSUE THREAD

**Issue by mikedo** [MPEGGroup/DASHSchema#82]
Validation tools do not type xs:anyUri very tightly resulting in typos in that type and dependent datatypes, e.g. @profiles.

**Comment by paulhiggs** [comment]
http://lists.xml.org/archives/xml-dev/200108/msg00891.html

Interestingly 
**However, we've found that (a) many customers actually use illegal URIs int heir documents happily, (b) XML Schema Part 2 (http://www.w3.org/TR/xmlschema-2/#anyURI) doesn't require any validation of the contents of the anyURI dataype, and (c) most customers don't want us to validate stronger than what other processors are doing.**

**Comment by mikedo** [comment]
The commercial validator tool vendors' view aside (the above quote is from one), we have issues in the DASH industry where @profiles, especially with a list, becomes unparsable by decoders, which is bad.  Let's see what happens in DASH-IF regression testing.

**Comment by paulhiggs** [comment]
I'm happy to strongly define @profiles to be "a comma separated list of URNs or URLs". The DTD ENTIRY definitions provided for `&URN;` and `&URL;` do this in `(&URN;|&URL;)(,(&URN;|&URL;))*`

Other `xs:anyURI` may need different validation, for example, if the specification says that the "element shall contain an ftp URL"

**Comment by mikedo** [comment]
FYI, it's worse than that. There are many (~100) URI schemes registered at IANA, such tag:, doi:, etc all valid URIs.

**Comment by paulhiggs** [comment]
If the DASH spec says "allow any URI" then we can make the cumbersome patterns for each. I suspect that we have just been lazy and do not need many of the URI schemes (for example `mailto:`) in some situations

**Comment by mikedo** [comment]
Consider adding "URI" which is a simple catchall that is just (from memory) <scheme> ":" <id> where the only constraint is that the tokens conform to the restricted charset. It would be tedious and high maintenance for not much value to verify registered URI scheme values as well as registered URN namespaces (both from IANA). If we're not going to do that, then URN devolves to URI above.

**Comment by mikedo** [comment]
{ah, mailto: makes me recall gopher: news: and other forgotten schemes from history)

**Comment by paulhiggs** [comment]
We can at least make a start by looking at any elements that are defined with the `xs:anyURI` datatype and then check the standard to see if there is any additional profiling, for example, I would expect that the `BaseURL` could be constrained to only http:// and https:// URLs which can be realized by defining `&http-url;` by copying `&URL;` and replacing the `&SchemeID;` in with `https?://`, ie `http` followed by 0 or 1 `s` characters (if that is to 'complicated' then `(http|https)://` also works

**Comment by mikedo** [comment]
Yes, if the spec imposes constraints on the URI syntax, we should, within reason, strive to capture that.

**Comment by paulhiggs** [comment]
> Yes, if the spec imposes constraints on the URI syntax, we should, within reason, strive to capture that.

5th edition defines (clause 5.3.1.2) that `MPD@profiles` needs to be a comma-separated list of URIs as defined in clause 8.1 which is an MPEG DASH URN or an externallt defined URN or URL.

Given this, and the implementation of `ListOfProfilesType` using the facet `<xs:pattern value="(&URN;|&URL;)(&comma_sep;(&URN;|&URL;))*"/>`, I believe we have this covered now through #86 and 14e0d55.

Can probably close this issue now.

**Comment by paulhiggs** [comment]
`MPD@profiles` is now covered so closing this issue.
Can create new issues is other elements or attributes need schema based checking
