### ISSUE TITLE
5th edition schema shows "Preroll" element in MPDType but 5th FDIS does not

### ISSUE THREAD

**Issue by paulhiggs** [MPEGGroup/DASHSchema#89]
The 5th edition schema shows the definition of `<xs:element name="Preroll" type="PeriodType" minOccurs="0" maxOccurs="unbounded"/>` in `MPDType` but this is not shown in section 5.3.1.3.

There is no mention of "Preroll" in the 5th edition FDIS draft

**Comment by paulhiggs** [comment]
Not sure if this is just a schema vs FDIS issue - seems &lt;Preroll&gt; is not in the FDIS at all - was this dropped?
See also [MPEG/Systems/DASH#2](http://mpegx.int-evry.fr/software/MPEG/Systems/DASH/spec/-/issues/2)

**Comment by paulhiggs** [comment]
&lt;Preroll&gt; added in #70. 

Should it be in the FDIS? [m55278](http://mpegx.int-evry.fr/software/MPEG/Systems/DASH/spec/-/issues/91) suggests Amd2

**Comment by mikedo** [comment]
> Not sure if this is just a schema vs FDIS issue - seems <Preroll> is not in the FDIS at all - was this dropped? See also MPEG/Systems/DASH#2
<p> I believe Preroll was deferred and should be removed from the 5th Ed.

**Comment by paulhiggs** [comment]
Will push a commit to remove &lt;Preroll&gt; from 5th edition schema
