### ISSUE TITLE
Frame Rate Values

### ISSUE THREAD

**Issue by sdp198** [MPEGGroup/DASHSchema#9]
How easy would it be to prevent the denominator in FrameRateType being 0? 

Also example G13-2 has demonators of 0.  Unless it's a test of client exception handling this seems wrong.

**Comment by mikedo** [comment]
There are many types defined in this schema which could be improved with tighter typing, which may include better patterns/RegEx.  These are most welcome. 

I don't know the genesis of G13-2, but in general (even if you believe in negative test vectors) these are examples and intentionally positive in nature.  Please propose a PR against the example.

**Comment by paulhiggs** [comment]
Specification pattern is 	<xs:pattern value="[0-9]*[0-9](/[0-9]*[0-9])?"/>
so changing these from frameRate="50/0" to frameRate="50" makes the most sense

That said, this pattern does not permit "30/1.001" i.e. 29.970

**Comment by paulhiggs** [comment]
if you want to ensure that the denominator does not allow '0' the pattern should be
`<xs:pattern value="[0-9]*[0-9](/[1-9][0-9]*)?"/>'
thus the denominator meaning becomes "a digit in the range 1-9 followed by zero or more digits in the range 0-9"
