### ISSUE TITLE
5th edition schema defines "Period" explicity, schema uses xs:ref

### ISSUE THREAD

**Issue by paulhiggs** [MPEGGroup/DASHSchema#90]
5th edition FDIS defines the `Period` element in `MPDType` as 
````
<xs:element name="Period" type="PeriodType" maxOccurs="unbounded"/>
````

5th edition schema refers to 'top level' `Period` element
````
<xs:element ref="Period" maxOccurs="unbounded"/>
````

**Comment by paulhiggs** [comment]
related to #78 and #91

**Comment by mikedo** [comment]
The schemas in the draft FDIS are *not* authoritative, now or when it is published.  The electronic schemas are.  The FDIS schemas need to follow the intent of the text.  When we're done with the electronic schemas, Thomas will copy/paste them verbatim into the FDIS text.
