### ISSUE TITLE
no 'top level' Period element in 5th edition FDIS

### ISSUE THREAD

**Issue by paulhiggs** [MPEGGroup/DASHSchema#91]
Schema allows either <MPD> or <Period> to be the top level (root) elements in an XML document using the `urn:mpeg:dash:schema:mpd:2011` namespace.

5th edition FDIS does not permit this (clause 5.2.2 only defines &lt;MPD&gt;

**Comment by paulhiggs** [comment]
related to #78

**Comment by mikedo** [comment]
The AHG agreed that Period is not a top level element and text was created to state this explicitly. This needs to effectively restored to the 3rd Ed (no top level Period or anything else except MPD).

**Comment by paulhiggs** [comment]
Fixed with #90
