### ISSUE TITLE
Incorrect definition of ContentProtection element in RepresentationBaseType

### ISSUE THREAD

**Issue by paulhiggs** [MPEGGroup/DASHSchema#97]
5th edition FDIS changes the dataype of `ContentProtection` element in `RepresentationBaseType` from `DescriptorType` to `ContentDescriptorType`.

There is no such datatype named `ContentDescriptorType`! Should probably be `ContentProtectionType`

**Comment by haudiobe** [comment]
Agreed. Implemented in FDIS!

**Comment by paulhiggs** [comment]
Resolved in latest FDIS (2021-06-17)
