### ISSUE TITLE
Name corrections in revision information

### ISSUE THREAD

**Issue by paulhiggs** [MPEGGroup/DASHSchema#98]
Clause 5.2.3.5 says
> 5.2.3.5	Elements and Attributes added in the fifth edition (ISO/IEC 23009-1:2021)
> This revision adds the following elements and attributes to the schema defined in Annex B compared to the 2020 revision (ISO/IEC 23009-1:2020) of this document:
> —	MPD.ContentProtection
> —	MPD.PatchLocation
> —	Period.ContentProtection
> —	AdaptationSet@initializationPrincipal
> —	RepresentationBase.Resync
> —	RepresentationBase@containerProfile
> —	Representation.ExtendedBandwidth
> —	ContentProtection@ref
> —	ContentProtection@refId
> —	ContentProtection@robustness
> —	CommonAttributesAndElements.OutputProtection

`RepresentationBase@containerProfile` should be `RepresentationBase@containerProfiles`
`CommonAttributesAndElements.OutputProtection` should be `RepresentationBase.OutputProtection`

**Comment by haudiobe** [comment]
Thank you. Fixed in FDIS text.

**Comment by paulhiggs** [comment]
Resolved in latest FDIS (2021-06-17)
